export const all_routes = {
  //Auth routes
  login: "/login",
  loginCover: "/login-cover",
  loginillustration: "/login-illustration",
  loginbasic: "/login-basic",
  registercover: "/register-cover",
  registerillustration: "/register-illustration",
  registerbasic: "/register-basic",
  forgotpasswordcover: "/forgot-password-cover",
  forgotpasswordillustration: "/forgot-password-illustration",
  forgotpasswordbasic: "/forgot-password-basic",
  resetpasswordcover: "/reset-password-cover",
  resetpasswordillustration: "/reset-password-illustration",
  resetpasswordbasic: "/reset-password-basic",
  emailverificationcover: "/email-verification-cover",
  emailverificationillustration: "/email-verification-illustration",
  emailverificationbasic: "/email-verification-basic",
  twostepverificationcover: "/two-step-verification-cover",
  twostepverificationillustration: "/two-step-verification-illustration",
  twostepverificationbasic: "/two-step-verification-basic",
  lockscreen: "/lock-screen",
  error404: "/error-404",
  error500: "/error-500",
  successCover: "/success-cover",
  successIllustration: "/success-illustration",
  successBasic: "/success-basic",

  //Dashboard routes
  dashboard: "/dashboard",
  doctordashboard: "/doctor-dashboard/",
  patientdashboard: "/patient/patient-dashboard",
  clinicdashboard: "/clinic-dashboard/",

  //Patient
  patientdetails: "/patient/patient-details",
  patientappointments: "/patient/patient-appointments",
  patientappointmentdetails: "/patient/patient-appointment-details",
  patientdoctors: "/patient/patient-doctors",
  patientPrescriptions: "/patient/patient-prescriptions",
  patientinvoices: "/patient/patient-invoices",
  patientprofilesettings: "/patient/patient-profile-settings",
  patientpasswordsettings: "/patient/patient-password-settings",
  patientnotificationssettings: "/patient/patient-notifications-settings",
  patientprescriptiondetails: "/patient/patient-prescription-details",
  patientinvoicedetails: "/patient/patient-invoice-details",

  //Doctor
  doctorschedule: "/doctor/doctor-schedule",
  doctordetails: "/doctor/doctor-details",
  doctorreviews: "/doctor/doctors-reviews",
  doctorleaves: "/doctor/doctors-leaves",
  doctorsprofilesettings: "/doctor/doctors-profile-settings",
  doctorspasswordsettings: "/doctor/doctors-password-settings",
  doctorsnotificationsettings: "/doctor/doctors-notification-settings",
  doctorsprescriptions: "/doctor-dashboard/doctors-prescriptions",
  onlineconsultations: "/doctor-dashboard/consultations/add",
  doctorsappointments: "/doctor-dashboard/doctors-appointments",
  doctorspatientdetails: "/doctor/doctors-patient-details",
  doctorsappointmentdetails: "/doctor/doctors-appointment-details",
  doctorsprescriptiondetails: "/doctor-dashboard/doctors-prescription-details",
  doctorsconsultation: "/doctor-dashboard/consultations",

  //Super Admin routes
  superAdminDashboard: "/super-admin/super-admin-dashboard",
  companies: "/super-admin/companies",
  subscriptions: "/super-admin/subscriptions",
  packages: "/super-admin/packages",
  packagesGrid: "/super-admin/packages-grid",
  domain: "/super-admin/domain",
  purchaseTransaction: "/super-admin/purchase-transaction",

  //Application routes
  chat: "/application/chat",
  calendar: "/application/calendar",
  notes: "/application/notes",
  voiceCall: "/application/voice-call",
  videoCall: "/application/video-call",
  outgoingCall: "/application/outgoing-call",
  incomingCall: "/application/incoming-call",
  callHistory: "/application/call-history",
  todo: "/application/todo",
  todoList: "/application/todo-list",
  email: "/application/email",
  EmailReply: "/application/email-reply",
  audioCall: "/application/audio-call",
  fileManager: "/application/file-manager",
  socialFeed: "/application/social-feed",
  kanbanView: "/application/kanban-view",
  invoice: "/application/invoice",
  contacts: "/application/contacts",
  searchList: "/application/search-list",
  invoiceDetails: "/application/invoice-details",
  addInvoice: "/add-invoice",
  notifications:"/notifications",

  //Layout Routes
  layoutDefault: "/layout-default",
  layoutMini: "/layout-mini",
  layoutHoverView: "/layout-hover-view",
  layoutHidden: "/layout-hidden",
  layoutFullWidth: "/layout-full-width",
  layoutDark: "/layout-dark",
  layoutRTL: "/layout-rtl",

  //Clinic Pages
  doctors: "/doctors",
  doctorsList: "/doctors-list",
  doctorsDetails: "/doctor-details",
  addDoctors: "/add-doctor",
  editDoctors: "/edit-doctors",
  doctorScheduleClini: "/doctor-schedule",
  patients: "/patients",
  patientsGrid: "/patients-grid",
  editPatient: "/edit-patient",
  patientDetails: "/patient-details",
  createPatient: "/create-patient",
  appointments: "/appointments",
  newAppointment: "/new-appointment",
  editAppointment: "/edit-appointment",
  appointmentCalendar: "/appointment-calendar",
  locations: "/locations",
  services: "/services",
  specializations: "/specializations",
  assets: "/assets",
  activities: "/activities",
  messages: "/messages",
  appointmentconsultations: "/appointment-consultations",


  //Clinic 
  clinicList: "/clinic-list",
  addClinic: "/add-clinic",
  editClinic: "/edit-clinic",
  clinicDetails: "/clinic-details",

  //HRM Pages
  staffs: "/staffs",
  hrmDepartments: "/hrm-departments",
  designation: "/designation",
  attendance: "/attendance",
  leaves: "/leaves",
  leaveType: "/leave-type",
  holidays: "/holidays",
  payroll: "/payroll",
  payroll2: "/payroll-2",

  //Finance & Accounts
  expenses: "/expenses",
  expenseCategory: "/expense-category",
  income: "/income",
  invoices: "/invoices",
  invoicesDetails: "/invoices-details",
  addInvoices: "/add-invoices",
  editInvoices: "/edit-invoices",
  payments: "/payments",
  transactions: "/transactions",

  //Administration
  rolesPermissions: "/roles-and-permissions",
  permissions: "/permissions",
  deleteaccountrequest: "/delete-account-request",
  incomeReport: "/income-report",
  expenseReport: "/expense-report",
  profitloss: "/profit-and-loss",
  appointmentReport: "/appointment-report",
  patientReport: "/patient-report",

  //Content Page routes
  pages: "/pages",
  addPage: "/add-page",
  editPage: "/edit-page",
  blogs: "/blogs",
  addBlogs: "/add-blog",
  editBlogs: "/edit-blog",
  blogDetails: "/blog-details",
  blogCategories: "/blog-categories",
  blogTags: "/blog-tags",
  blogComments: "/blog-comments",
  countries: "/countries",
  states: "/states",
  cities: "/cities",
  testimonials: "/testimonials",
  faq: "/faq",

  //Support
  contactMessages: "/contact-messages",
  tickets: "/tickets",
  ticketDetails: "/ticket-details",
  announcements: "/announcements",
  newsletters: "/newsletters",

  //Pages routes
  profile: "/profile",
  starter: "/starter",
  gallery: "/gallery",
  pricing: "/pricing",
  timeline: "/timeline",
  comingSoon: "/coming-soon",
  underMaintenance: "/under-maintenance",
  underConstruction: "/under-construction",
  apiKeys: "/api-keys",
  privacyPolicy: "/privacy-policy",
  termsCondition: "/terms-condition",

  //Settings
  profilesettings: "/profile-settings",
  securitysettings: "/security-settings",
  notificationssettings: "/notifications-settings",
  integrationssettings: "/integrations-settings",
  organizationsettings: "/organization-settings",
  localizationsettings: "/localization-settings",
  prefixessettings: "/prefixes-settings",
  seosetupsettings: "/seo-setup-settings",
  languagesettings: "/language-settings",
  languagesettings2: "/language-settings2",
  languagesettings3: "/language-settings3",
  maintenancemodesettings: "/maintenance-mode-settings",
  loginandregistersettings: "/login-and-register-settings",
  preferencessettings: "/preferences-settings",
  appointmentsettings: "/appointment-settings",
  workinghourssettings: "/working-hours-settings",
  cancellationreasonsettings: "/cancellation-reason-settings",
  invoicesettings: "/invoice-settings",
  invoicetemplatessettings: "/invoice-templates-settings",
  signaturessettings: "/signatures-settings",
  customfieldssettings: "/custom-fields-settings",
  emailsettings: "/email-settings",
  emailtemplatessettings: "/email-templates-settings",
  smsgatewayssettings: "/sms-gateways-settings",
  smstemplatessettings: "/sms-templates-settings",
  gdprcookiessettings: "/gdpr-cookies-settings",
  paymentmethodssettings: "/payment-methods-settings",
  bankaccountssettings: "/bank-accounts-settings",
  taxratessettings: "/tax-rates-settings",
  currenciessettings: "/currencies-settings",
  sitemapsettings: "/sitemap-settings",
  clearcachesettings: "/clear-cache-settings",
  storagesettings: "/storage-settings",
  cronjobsettings: "/cronjob-settings",
  banipaddresssettings: "/ban-ip-address-settings",
  systembackupsettings: "/system-backup-settings",
  databasebackupsettings: "/database-backup-settings",
  systemupdate: "/system-update",

  //Ui Imterface
  dragula: "/extended-dragula",
  uiAccordion: "/ui-accordion",
  uiAlerts: "/ui-alerts",
  uiAvatar: "/ui-avatar",
  uiBadges: "/ui-badges",
  uiBreadcrumb: "/ui-breadcrumb",
  uiButtons: "/ui-buttons",
  uiButtonsGroup: "/ui-buttons-group",
  uiCards: "/ui-cards",
  uiCarousel: "/ui-carousel",
  uiCollapse: "/ui-collapse",
  uiDropdowns: "/ui-dropdowns",
  uiRatio: "/ui-ratio",
  uiGrid: "/ui-grid",
  uiImages: "/ui-images",
  uiLinks: "/ui-links",
  uiListGroup: "/ui-list-group",
  uiModals: "/ui-modals",
  uiOffcanvas: "/ui-offcanvas",
  uiPagination: "/ui-pagination",
  uiPlaceholders: "/ui-placeholders",
  uiPopovers: "/ui-popovers",
  uiProgress: "/ui-progress",
  uiScrollspy: "/ui-scrollspy",
  uiSpinner: "/ui-spinner",
  uiNavTabs: "/ui-nav-tabs",
  uiToasts: "/ui-toasts",
  uiTooltips: "/ui-tooltips",
  uiTypography: "/ui-typography",
  uiUtilities: "/ui-utilities",
  uiDraggble: "/extended-dragula",
  uiClipboard: "/ui-clipboard",
  uiRangeslider: "/ui-rangeslider",
  uiLightbox: "/ui-lightbox",
  uiRating: "/ui-rating",
  uiCounter: "/ui-counter",
  uiScrollbar: "/ui-scrollbar",

  chartApex: "/chart-apex",
  chartJs: "/chart-js",

  mapsLeaflet: "/maps-leaflet",

  tablesBasic: "/tables-basic",
  dataTables: "/data-tables",

  iconFontawesome: "/icon-fontawesome",
  iconTabler: "/icon-tabler",
  iconBootstrap: "/icon-bootstrap",
  iconRemix: "/icon-remix",
  iconIonic: "/icon-ionic",
  iconMaterial: "/icon-material",
  iconPe7: "/icon-pe7",
  iconThemify: "/icon-themify",
  iconWeather: "/icon-weather",
  iconTypicon: "/icon-typicon",
  iconFlag: "/icon-flag",

  formBasicInputs: "/form-basic-inputs",
  formCheckboxRadios: "/form-checkbox-radios",
  formInputGroups: "/form-input-groups",
  formGridGutters: "/form-grid-gutters",
  formFileupload: "/form-fileupload",
  formHorizontal: "/form-horizontal",
  formVertical: "/form-vertical",
  formFloatingLabels: "/form-floating-labels",
  formValidation: "/form-validation",
  formSelect2: "/form-select2",
  formPickers: "/form-pickers",
  formWizard: "/form-wizard",
  formMask: "/form-mask",

//------Clinic Panel
 clinicadddoctor: "/clinic-dashboard/add-doctor",
 clinicallDoctors: "/clinic-dashboard/doctors-list",
 cliniceditDoctors: "/clinic-dashboard/edit-doctor",
 clinicdoctordetails: "/clinic-dashboard/doctor-details",


 clinicappointments: "/clinic-dashboard/appointments",
 clinicnewAppointments: "/clinic-dashboard/new-appointments",
 cliniceditAppointments: "/clinic-dashboard/edit-appointments",

   clinicpatients: "/clinic-dashboard/patients",
   cliniccreatePatient: "/clinic-dashboard/create-patient",
   cliniceditPatient: "/clinic-dashboard/edit-patient",
   clinicpatientdetails: "/clinic-dashboard/patient-details",


   clinicaddDoctorsCopy: "/clinic-dashboard/add-doctor-copy",


  //------- Medicine
 addMedicine: "/add-medicine",
 MedicineList: "/medicines-list",
 editMedicine: "/edit-medicine",

 //------- Procedure
 addProcedure: "/add-procedure",
 ProcedureList: "/procedure-list",
 editProcedure: "/edit-procedure",

  //------- Billing
  addmaterialpurchasebill: "/add-material-purchase-bill",
  materialpurchasebillList: "/material-purchase-bills",
  editmaterialpurchasebill: "/edit-material-purchase-bill",
  viewmaterialpurchasebill: "/view-material-purchase-bill",

  addclinicbill: "/add-clinic-bill",
  clinicbillList: "/clinic-bill",
  editclinicbill: "/edit-clinic-bill",
  viewclinicbill: "/view-clinic-bill",

  addlabbill: "/add-lab-bill",
  labbillList: "/lab-bill",
  editlabbill: "/edit-lab-bill",
  viewlabbill: "/view-lab-bill",


  addpharmacybill: "/add-pharmacy-bill",
  pharmacybillList: "/pharmacy-bill",
  editpharmacybill: "/edit-pharmacy-bill",
  viewpharmacybill: "/view-pharmacy-bill",
  

  //------- Clinic Billing
    clinicaddclinicbill: "/clinic-dashboard/add-clinic-bill",
    clinicpanelclinicbillList: "/clinic-dashboard/clinic-bill",
    cliniceditclinicbill: "/clinic-dashboard/edit-clinic-bill",
    clinicviewclinicbill: "/clinic-dashboard/view-clinic-bill",

    clinicaddlabbill: "/clinic-dashboard/add-lab-bill",
    clinicpanellabbillList: "/clinic-dashboard/lab-bill",
    cliniceditlabbill: "/clinic-dashboard/edit-lab-bill",
    clinicviewlabbill: "/clinic-dashboard/view-lab-bill",


    clinicaddmaterialpurchasebill: "/clinic-dashboard/add-material-purchase-bill",
    clinicmaterialpurchasebillList: "/clinic-dashboard/material-purchase-bills",
    cliniceditmaterialpurchasebill: "/clinic-dashboard/edit-material-purchase-bill",
    clinicviewmaterialpurchasebill: "/clinic-dashboard/view-material-purchase-bill",

    clinicaddpharmacybill: "/clinic-dashboard/add-pharmacy-bill",
    clinicpharmacybillList: "/clinic-dashboard/pharmacy-bill",
    cliniceditpharmacybill: "/clinic-dashboard/edit-pharmacy-bill",
    clinicviewpharmacybill: "/clinic-dashboard/view-pharmacy-bill",



    clinicPrescriptions: "/clinic-dashboard/prescriptions",
    clinicPrescriptionsdetails: "/clinic-dashboard/prescriptions-details",
    
    printPharmacyBill: "/clinic/pharmacy-bill/print/:billId",

};
